name = "cf-r2-webdav"
main = "src/index.ts"
compatibility_date = "2023-01-01"

[vars]
USERNAME = "bear666"
PASSWORD = "Ljsh090506"
BUCKET_NAME = "webdav"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "webdav"
